-- You can use this file to load seed data into the database using SQL statements
INSERT INTO USER VALUES(1, 'admin@demoiselle.org', 'Admin', 'e10adc3949ba59abbe56e057f20f883e', 'ADMIN');
INSERT INTO TODO (ID, CHANGED, DATEEND, DESCRIPTION, STATUS, USER_ID) VALUES(RANDOM_UUID(), 0, CURRENT_DATE(), 'tarefa 1', 'pendente', 1);
INSERT INTO TODO (ID, CHANGED, DATEEND, DESCRIPTION, STATUS, USER_ID) VALUES(RANDOM_UUID(), 0, CURRENT_DATE(), 'tarefa 2', 'pendente', 1);
INSERT INTO TODO (ID, CHANGED, DATEEND, DESCRIPTION, STATUS, USER_ID) VALUES(RANDOM_UUID(), 0, CURRENT_DATE(), 'tarefa 3', 'pendente', 1);

INSERT INTO USER VALUES(2, 'usuario@demoiselle.org', 'Usuario', 'e10adc3949ba59abbe56e057f20f883e', 'USER');
INSERT INTO TODO (ID, CHANGED, DATEEND, DESCRIPTION, STATUS, USER_ID) VALUES(RANDOM_UUID(), 0, CURRENT_DATE(), 'tarefa 1', 'pendente', 2);
INSERT INTO TODO (ID, CHANGED, DATEEND, DESCRIPTION, STATUS, USER_ID) VALUES(RANDOM_UUID(), 0, CURRENT_DATE(), 'tarefa 2', 'pendente', 2);
INSERT INTO TODO (ID, CHANGED, DATEEND, DESCRIPTION, STATUS, USER_ID) VALUES(RANDOM_UUID(), 0, CURRENT_DATE(), 'tarefa 3', 'pendente', 2);
